name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          APP_DIR="/var/www/homepages_backend"

          # clone or pull
          if [ ! -d "$APP_DIR/.git" ]; then
            git clone https://github.com/${{ github.repository }} $APP_DIR
          else
            cd $APP_DIR
            git reset --hard
            git pull origin main
          fi

          cd $APP_DIR

          echo ">>> 安装依赖"
          npm install --production

          echo ">>> 重启应用"
          pm2 restart homepages_backend || pm2 start npm --name "homepages_backend" -- run start
          EOF
